#!/usr/local/bin/python3.7

from utils.ConfManager import Configuration
from utils.Dynamo import Dynamo
from utils.FileManager import FileManager
from utils.S3 import S3

from datetime import datetime
from time import strftime
from tqdm import tqdm
import os
import sys

if __name__ == '__main__':
    # Load configuration
    # Pass command line params
    configuration = Configuration(sys.argv[1:])
    
    # Create /tmp folder (where the output files are stored)
    os.system("mkdir -p tmp")
    print("[CONF] Tablename: {}  AWS region: {}  File size: {}  Output format: {}  Bucket name: {}  Path on S3: {}  Delete Items: {}".format(
        configuration.conf["tablename"], 
        configuration.conf["aws_region"], 
        configuration.conf["limit_per_file"],
        configuration.conf["output_format"],
        configuration.conf["bucket_name"],
        configuration.conf["bucket_path"],
        configuration.conf["delete_items"],
    ))
    # Get Items from DB
    db = Dynamo(
        configuration.conf["tablename"], 
        configuration.conf["aws_region"]
    )
    items = db.fetch_all_items(configuration.conf["limit_per_file"])
    print("[INFO] {} items found".format(len(items)))
                                                                                                                                    
    # Write file
    fm = FileManager()
    filename =  "{}_{}.{}".format(
        configuration.conf["filename"],
        datetime.now().strftime("%Y-%m-%d_%H:%M:%S"),
        configuration.conf["output_format"])
    if "json" == configuration.conf["output_format"]:
        fm.write_json(items, filename)
    else:
        fm.write_csv(items, filename)

    # Upload file on S3
    s3 = S3()
    if s3.upload_s3(
        configuration.conf["bucket_name"], 
        configuration.conf["bucket_path"], 
        filename):
        if configuration.conf["delete_items"]:
            # Delete items in Dynamo
            db.delete_items(items)
        else:
            print("[INFO] Items not deleted.")
    print("[DONE]")